### ISSUE TITLE
Paragraph numbering messed up in preview

### ISSUE THREAD

**Issue by tlongers** [official-inquiries/uk-parliament-20160706-iraq-inquiry#2]
Though text and markdown is correct,  paragraph numbering  is rendered as new ordered list each time. Here's an example.

Original text from  [source PDF of Introduction](https://github.com/official-inquiries/uk-parliament-20160706-iraq-inquiry/blob/master/archive/the-report-of-the-iraq-inquiry_introduction.pdf).

![the-report-of-the-iraq-inquiry_introduction_pdf__page_2_of_19_](https://cloud.githubusercontent.com/assets/2115933/16688888/1bb00ee0-4518-11e6-971b-7af08d67c095.png)

The Markdown version of the [same text](https://github.com/official-inquiries/uk-parliament-20160706-iraq-inquiry/blob/master/markdown/volume-1/introduction.md#purpose-of-the-inquiry) has this:

`2. Addressing the scope of the Inquiry, Mr Brown said: ...`

This renders as the below in [Marked2](http://marked2app.com/) and [Github](https://github.com/official-inquiries/uk-parliament-20160706-iraq-inquiry/blob/master/markdown/volume-1/introduction.md):
![introduction_md__80__](https://cloud.githubusercontent.com/assets/2115933/16688850/f472f45a-4517-11e6-8df8-a32db5b424e6.png)

Is the correct approach to escape the period after the number where the paragraph is numbered?

**Comment by GregoryRhysEvans** [comment]
Yes, that is correct. Right now, this isn't a top priority, but we will need a way to fix this in future.

**Comment by tlongers** [comment]
Doing it manually for initial commits of Markdown formatted versions. Guess it can be scripted later.
