### ISSUE TITLE
Handling of footnotes in MD formatted versions

### ISSUE THREAD

**Issue by tlongers** [official-inquiries/uk-parliament-20160706-iraq-inquiry#5]
I can see three options for footnotes:
- Leave footnotes in text as is
- Format with reference links in Markdown
- Remove from text and deal with them later on

Which is preferred here?

**Comment by rufuspollock** [comment]
We should correct footnotes to proper markdown footnotes IMO.

**Comment by tlongers** [comment]
Using MultiMarkdown formatting as described [here](https://github.com/fletcher/MultiMarkdown/wiki/MultiMarkdown-Syntax-Guide#footnotes).
